### ISSUE TITLE
Listado de Aventuras oficiales

### ISSUE THREAD

**Issue by rmoliva** [diacritica/codexlmde#1]
- [x] El Legado Perdido
- [x] B1 La Cripta nefanda de Uztum el Maldito
- [x] B2 La Isla Misteriosa
- [x] B3 El Orbe de Amonhotep
- [x] B4 Muerte en la Mansión del Mago Malifax
- [x] B5 Incursión a la Tierra del Dios Azul
- [x] B6 Tiempo fuera del tiempo
- [x] B7 Presentes Sangrientos
- [x] B8 La Tumba del hielo
- [x] B9 La última Frontera
- [x] B10 El túmulo perdido de Azgoz el Testarudo
- [x] B11 Las Cuevas del Clan Atronador
- [x] X1 En busca del a ciudad perdida de Garan
- [x] X2 El Arca de los mil Inviernos
- [x] C1 Los Salones Anegados de Leviathán
- [x] C2 Las catacumbas de los espantos de Kavaduz
- [x] C3 El Jardín Negro
- [x] TN1 Pacto de Cenizas
- [x] TN2 El Feudo en Llamas
- [x] TN3 El Corazón de la Oscuridad
- [x] G1 Un Paseo por el Campo
- [x] G2 Alameda
- [x] G3 Las Frondas de los Medianos
- [x] CT1 La Lágrima de Zurah
- [x] SP1 Tomo de Magia
- [x] V1 El castillo prohibido de la Reina de Sangre
- [x] ES1 La furia de Rastilón
- [x] MN1 Marjalnegro
- [x] BS1 Bestiario de Criaturas Extraordinarias

**Comment by logoff** [comment]
Hola @rmoliva. Si quieres añado las fichas de las aventuras oficiales que faltan, con la información que tengo. Solo faltaría después añadir los ficheros PDF para la descarga. Puedo dejar un PR parcial hecho en pocos días. ¿Qué te parece?

**Comment by diacritica** [comment]
actualizado a 12 de marzo
