### ISSUE TITLE
Problemas ordenando la Lista de Aventuras en https://test.codexdelamarca.com/allposts/

### ISSUE THREAD

**Issue by mascogo** [diacritica/codexlmde#11]
Con el Título, hay actividad, pero el orden no parece correcto.
Autoría, Carácter y el resto de columnas numéricas parecen funcionar bien, pero ordenan como texto, así, 1 y 10 van juntos, como ya han comentado.
Y Fecha Pub no funciona. La tabla no se mueve cuando se pincha en esta columna.

Uso Firefox.

**Comment by rmoliva** [comment]
Arreglado en https://github.com/diacritica/codexlmde/pull/12
