### ISSUE TITLE
Aventura Comunidad  "un Buen Vino"

### ISSUE THREAD

**Issue by Medaun** [diacritica/codexlmde#124]
aventura Onepage, para subir al codex

https://t.me/c/1386363014/3617

**Comment by rmoliva** [comment]
Hola @Medaun me he puesto a dar de alta esta aventura... pero creo que ya está: https://codexdelamarca.com/posts/un-buen-vino/

**Comment by rmoliva** [comment]
Estoy viendo que las aventuras son distintas, pero con el mismo título. Qué hacemos?

**Comment by Medaun** [comment]
se hablo por el grupo que hablare con el autor antes por si pudiera haber una solucion......
de todas formas no veo un gran problema porque las etiquetas/ y el autor son diferentes
pero aun asi vere de buscar un apaño

**Comment by Medaun** [comment]
se ha consultado al autor y sustituiremos el Titulo por "Un buen Licor" que queda similar y no entra en conflicto con el otro titulo.
