### ISSUE TITLE
Listado de Aventuras no oficiales

### ISSUE THREAD

**Issue by rmoliva** [diacritica/codexlmde#2]
- [x] La isla roja
- [x] La montaña soberana
- [x] El Signo Rojo
- [x] El tesoro del Torreón Negro
- [x] La Cripta de las Sombras (nivel 1)
- [x] Noches de venganza
- [x] La torre dimensional
- [x] Por unas tinajas de miel
- [x] El Pueblo Bendecido
- [x] El oro de las quebradas
- [x] Serpientes entre las ramas
- [x] El último viaje de “El Condenado”
- [x] El Santuario olvidado
- [x] Hojas gemelas
- [x] La caída de los justos

**Comment by Tersoal** [comment]
Más aventuras no oficiales, que habría que contrastar pero que siendo Sinergia de Rol todo apunta a que son buenas.

http://www.sinergiaderol.com/aventuras/av-aventurasmarcadeleste.html

**Comment by Tersoal** [comment]
Más recursos recopilados del chat de Jitsi:

https://immadon.mforos.com/1383824/12868585-aventuras-en-la-marca-del-este/

**Comment by Medaun** [comment]
Todas las aventuras, antes mencionadas están ya en el codex.
