### ISSUE TITLE
Los nombres de los autores aparecen con guiones

### ISSUE THREAD

**Issue by jccasais** [diacritica/codexlmde#20]
En el listado de nombres de autores, los nombres compuestos y apellidos salen separados con guiones no con espacios.
![Screenshot_20210429_185818](https://user-images.githubusercontent.com/83419038/116589579-1405c400-a91d-11eb-9379-ec9700ae4f71.jpg)

**Comment by Tersoal** [comment]
Hola. Ya tengo esto solucionado, pero antes de hacer el PR, quiero preguntar. Las etiquetas tienen un formato distinto (etiquetas negras en lugar de blancas, como en autores o líneas). Es decisión por diseño o hago estándar como los autores. Ocurre lo mismo con el nivel minimo y maximo, aunque no encuentro cómo llegar a esas páginas. Modifico también al menos las etiquetas para que se vena iguales que los autores?

**Comment by diacritica** [comment]
Yo creo que es OK unificar con fondo blanco todo, sí, avanti
