### ISSUE TITLE
Ordenación por título usa el enlace en lugar del título para ordenar

### ISSUE THREAD

**Issue by mascogo** [diacritica/codexlmde#41]
Buenas, hace tiempo que no participo, pero estaba mirando hoy la página, intentando ordenar todos los módulos por título, y veo que algunos no se ordenan bien. 
Me he dado cuenta de que, cuando ordenas por título, realmente está ordenando por el path del enlace.

Hay dos módulos "B" que no tienen el código en el nombre del enlace, y por eso se descuadran en la lista: 

el B8 y el B11

También hay otros módulos que en el nombre de carpeta de la URL no está el código, y tampoco se ordenan en condiciones.

Si se ordenaran por la columna Título en lugar de por el URL, se ordenarían mejor

**Comment by rmoliva** [comment]
Creo que esto ya lo corrigió Pablo en su momento...
