### ISSUE TITLE
corregir archivo en cronicas de la marca sustituir  https://t.me/c/1386363014/2758      Empezamos. Aqui va el archivo para sustituir en el reglamento del Codex, El Pdf de  cronicas por este Rar, que incluye los mapas de la aventura interior..... Yo añadiria tambien en la descripcion final:  Se incluyen en el archivo los mapas para jugar la aventura introductoria "Ecos del Pasado" incluida en el manual.

### ISSUE THREAD

**Issue by Medaun** [diacritica/codexlmde#63]

**Comment by rmoliva** [comment]
Perdona @Medaun no entiendo que diferencia hay entre este y el: https://github.com/diacritica/codexlmde/issues/69

**Comment by rmoliva** [comment]
No he modificado la última parte del ticket: "Yo añadiria tambien en la descripcion final: Se incluyen en el archivo los mapas para jugar la aventura introductoria "Ecos del Pasado" incluida en el manual.:" Por el comentario de Pedro: https://t.me/c/1386363014/2760
