### ISSUE TITLE
FAQ Cronicas de la Marca

### ISSUE THREAD

**Issue by Medaun** [diacritica/codexlmde#95]
Tal como se ha hablado por el grupo pongo aqui las FAQ de cronicas escritas por Cabo Hicks.
No se como se puede solucionar exactamente este añadido si bien poniendo un segundo enlace de descarga o de algun otro modo. 

https://t.me/c/1386363014/3209

**Comment by diacritica** [comment]
añadimos 

<p><a href="../downloads/FAQ-Cronicas_Marca_del_Este.pdf" target="_blank">FAQ La Marca Estelar</a></p>

a cada descripción de aventura de La Marca Estelar
